python ROUSFinder2.0.py -gb -m 15 ../../../Organelle_assemblies/mt_assembly/misc/Aeginetia_indica.fasta -b /usr/local/bin/
python ROUSFinder2.0.py -gb -m 15 ../../../Organelle_assemblies/mt_assembly/misc/Alectra_sessiflora_LM143.fasta -b /usr/local/bin/
python ROUSFinder2.0.py -gb -m 15 ../../../Organelle_assemblies/mt_assembly/misc/Aphyllon_fasciculatum.fasta -b /usr/local/bin/
python ROUSFinder2.0.py -gb -m 15 ../../../Organelle_assemblies/mt_assembly/misc/Aphyllon_purpureum.fasta -b /usr/local/bin/
python ROUSFinder2.0.py -gb -m 15 ../../../Organelle_assemblies/mt_assembly/misc/Aureolaria_grandiflora_LM037.fasta -b /usr/local/bin/
python ROUSFinder2.0.py -gb -m 15 ../../../Organelle_assemblies/mt_assembly/misc/Bartsia_inaequalis_LM033.fasta -b /usr/local/bin/
python ROUSFinder2.0.py -gb -m 15 ../../../Organelle_assemblies/mt_assembly/misc/Bellardia_latifolia_LM121.fasta -b /usr/local/bin/
python ROUSFinder2.0.py -gb -m 15 ../../../Organelle_assemblies/mt_assembly/misc/Brandisia_kwangsiensis_LM122.fasta -b /usr/local/bin/
python ROUSFinder2.0.py -gb -m 15 ../../../Organelle_assemblies/mt_assembly/misc/Castilleja_indivisa_LM001.fasta -b /usr/local/bin/
python ROUSFinder2.0.py -gb -m 15 ../../../Organelle_assemblies/mt_assembly/misc/Castilleja_paramensis_mitome.fasta -b /usr/local/bin/
python ROUSFinder2.0.py -gb -m 15 ../../../Organelle_assemblies/mt_assembly/misc/Centranthera_chevalieri_LM117.fasta -b /usr/local/bin/
python ROUSFinder2.0.py -gb -m 15 ../../../Organelle_assemblies/mt_assembly/misc/Christisonia_kwangtungensis.fasta -b /usr/local/bin/
python ROUSFinder2.0.py -gb -m 15 ../../../Organelle_assemblies/mt_assembly/misc/Cistanche_deserticola.fasta -b /usr/local/bin/
python ROUSFinder2.0.py -gb -m 15 ../../../Organelle_assemblies/mt_assembly/misc/Cistanche_salsa_ON890402-407.fasta -b /usr/local/bin/
python ROUSFinder2.0.py -gb -m 15 ../../../Organelle_assemblies/mt_assembly/misc/Cistanche_tubulosa_ON890408-419.fasta -b /usr/local/bin/
python ROUSFinder2.0.py -gb -m 15 ../../../Organelle_assemblies/mt_assembly/misc/Conopholis_alpina_LM013.fasta -b /usr/local/bin/
python ROUSFinder2.0.py -gb -m 15 ../../../Organelle_assemblies/mt_assembly/misc/Conopholis_americana_LM096.fasta -b /usr/local/bin/
python ROUSFinder2.0.py -gb -m 15 ../../../Organelle_assemblies/mt_assembly/misc/Epifagus_virginiana_LM036.fasta -b /usr/local/bin/
python ROUSFinder2.0.py -gb -m 15 ../../../Organelle_assemblies/mt_assembly/misc/Escobedia_crassipes_LM051.fasta -b /usr/local/bin/
python ROUSFinder2.0.py -gb -m 15 ../../../Organelle_assemblies/mt_assembly/misc/Euphrasia_cuspidata_LM030.fasta -b /usr/local/bin/
python ROUSFinder2.0.py -gb -m 15 ../../../Organelle_assemblies/mt_assembly/misc/Harveya_capensis.fasta -b /usr/local/bin/
python ROUSFinder2.0.py -gb -m 15 ../../../Organelle_assemblies/mt_assembly/misc/Hyobanche_sanguinea_LM077.fasta -b /usr/local/bin/
python ROUSFinder2.0.py -gb -m 15 ../../../Organelle_assemblies/mt_assembly/misc/Kopsiopsis_strobilacea_LM081.fasta -b /usr/local/bin/
python ROUSFinder2.0.py -gb -m 15 ../../../Organelle_assemblies/mt_assembly/misc/Lathraea.fasta -b /usr/local/bin/
python ROUSFinder2.0.py -gb -m 15 ../../../Organelle_assemblies/mt_assembly/misc/Lindenbergia_grandiflora_LM085.fasta -b /usr/local/bin/
python ROUSFinder2.0.py -gb -m 15 ../../../Organelle_assemblies/mt_assembly/misc/Mannagettaea_hummelii_LM093.fasta -b /usr/local/bin/
python ROUSFinder2.0.py -gb -m 15 ../../../Organelle_assemblies/mt_assembly/misc/Melasma_hispidum_LM109.fasta -b /usr/local/bin/
python ROUSFinder2.0.py -gb -m 15 ../../../Organelle_assemblies/mt_assembly/misc/Monochasma_japonicum_LM161.fasta -b /usr/local/bin/
python ROUSFinder2.0.py -gb -m 15 ../../../Organelle_assemblies/mt_assembly/misc/Odontites_serotina_LM136.fasta -b /usr/local/bin/
python ROUSFinder2.0.py -gb -m 15 ../../../Organelle_assemblies/mt_assembly/misc/Orobanche_austrohispanica_LM103.fasta -b /usr/local/bin/
python ROUSFinder2.0.py -gb -m 15 ../../../Organelle_assemblies/mt_assembly/misc/Orobanche_cooperi_LM014.fasta -b /usr/local/bin/
python ROUSFinder2.0.py -gb -m 15 ../../../Organelle_assemblies/mt_assembly/misc/Orobanche_crenata_LM102.fasta -b /usr/local/bin/
python ROUSFinder2.0.py -gb -m 15 ../../../Organelle_assemblies/mt_assembly/misc/Orobanche_dugesii_LM098.fasta -b /usr/local/bin/
python ROUSFinder2.0.py -gb -m 15 ../../../Organelle_assemblies/mt_assembly/misc/Orobanche_fasciculata_LM020.fasta -b /usr/local/bin/
python ROUSFinder2.0.py -gb -m 15 ../../../Organelle_assemblies/mt_assembly/misc/Orobanche_foetida_LM101.fasta -b /usr/local/bin/
python ROUSFinder2.0.py -gb -m 15 ../../../Organelle_assemblies/mt_assembly/misc/Orobanche_ludoviciana_LM016.fasta -b /usr/local/bin/
python ROUSFinder2.0.py -gb -m 15 ../../../Organelle_assemblies/mt_assembly/misc/Orobanche_minor_LM097.fasta -b /usr/local/bin/
python ROUSFinder2.0.py -gb -m 15 ../../../Organelle_assemblies/mt_assembly/misc/Orobanche_pinorum_LM099.fasta -b /usr/local/bin/
python ROUSFinder2.0.py -gb -m 15 ../../../Organelle_assemblies/mt_assembly/misc/Orobanche_ramosa_LM019.fasta -b /usr/local/bin/
python ROUSFinder2.0.py -gb -m 15 ../../../Organelle_assemblies/mt_assembly/misc/Orthocarpus_attenuatus_LM105.fasta -b /usr/local/bin/
python ROUSFinder2.0.py -gb -m 15 ../../../Organelle_assemblies/mt_assembly/misc/Pedicularis_attollens_LM040.fasta -b /usr/local/bin/
python ROUSFinder2.0.py -gb -m 15 ../../../Organelle_assemblies/mt_assembly/misc/Pedicularis_chinensis.fasta -b /usr/local/bin/
python ROUSFinder2.0.py -gb -m 15 ../../../Organelle_assemblies/mt_assembly/misc/Rehmannia_glutinosa.fasta -b /usr/local/bin/
